### ISSUE TITLE
Wrong module name on the blog post

### ISSUE THREAD

**Issue by matiasleidemer** [jodosha/lotus-api-example#1]
Hey there, thanks for sharing this!

I'm following your post, but there's a wrong module name in the snippet for the `ApiHelper`:

``` ruby
#...
def app
  Bookshelf::V1::Application.new
end
```

Though the correct would be:

``` ruby
#...
def app
  Bookshelf::API::Application.new
end
```

**Comment by jodosha** [comment]
@matiasleidemer Hey thank you, I've fixed it!
